FROM ghcr.io/ublue-os/fedora-toolbox:latest

COPY build-files /tmp/build-files

RUN dnf -y upgrade && \
    dnf -y install $(</tmp/build-files/packages) && \
    dnf clean all

RUN /tmp/build-files/packages-misc.sh

RUN ln -sf /usr/bin/distrobox-host-exec /usr/bin/flatpak && \
    ln -sf /usr/bin/distrobox-host-exec /usr/bin/tailscale && \
    ln -sf /usr/bin/distrobox-host-exec /usr/bin/podman && \
    ln -sf /usr/bin/distrobox-host-exec /usr/bin/rpm-ostree && \
    ln -sf /usr/bin/distrobox-host-exec /usr/bin/distrobox && \
    ln -sf /usr/bin/distrobox-host-exec /usr/bin/code

RUN rm -rf /tmp/build-files