FROM ghcr.io/ublue-os/fedora-toolbox:latest

COPY scripts /scripts
COPY toolboxes/fedora-dev-toolbox/packages.sh /scripts/

RUN /scripts/distrobox-shims.sh
RUN /scripts/packages.sh
RUN rm -rf /scripts